# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0a4f57c6f2803211055e011288accb6"
application_url = "https://bulk-price-editor-lilac.vercel.app"
embedded = true
name = "Bulk Price Editor"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_themes,write_themes,write_orders,read_orders,read_customers,write_customers,write_markets,read_markets"

[auth]
redirect_urls = [
  "https://bulk-price-editor-lilac.vercel.app/auth/callback",
  "https://bulk-price-editor-lilac.vercel.app/shopify/callback",
  "https://bulk-price-editor-lilac.vercel.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
